# Generated by Django 6.1.1 on 2026-09-21 11:35

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('listing_type', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('investment', 'Investment'), ('plots', 'Plots')], default='buy', max_length=20)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('new_launch', 'New Launch'), ('plot', 'Plot / Land')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('price_on_request', 'Price on Request'), ('coming_soon', 'Coming Soon')], default='active', max_length=20)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('locality', models.CharField(db_index=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100, validators=[apps.core.validators.validate_rera_number])),
                ('is_rera_verified', models.BooleanField(db_index=True, default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for Price on Request', max_digits=14, null=True, validators=[apps.core.validators.validate_positive_price])),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[apps.core.validators.validate_positive_price])),
                ('developer_name', models.CharField(blank=True, max_length=200)),
                ('total_area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('roi_potential', models.DecimalField(blank=True, decimal_places=2, help_text='ROI percentage, e.g. 14.0 for 14%', max_digits=5, null=True)),
                ('rental_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Rental yield percentage, e.g. 5.6 for 5.6%', max_digits=5, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_gift_city', models.BooleanField(db_index=True, default=False)),
                ('is_zero_brokerage', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list, help_text='["RERA Verified", "Zero Brokerage"]')),
                ('meta_title', models.CharField(blank=True, max_length=70, validators=[apps.core.validators.validate_meta_title])),
                ('meta_description', models.CharField(blank=True, max_length=160, validators=[apps.core.validators.validate_meta_description])),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/', validators=[apps.core.validators.validate_pdf_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing_type', 'property_type'], name='properties__listing_f4dc22_idx'), models.Index(fields=['city', 'locality'], name='properties__city_23f8c1_idx'), models.Index(fields=['is_featured', 'status'], name='properties__is_feat_66aedb_idx'), models.Index(fields=['price'], name='properties__price_32e7c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', validators=[apps.core.validators.validate_image_file])),
                ('alt_text', models.CharField(blank=True, help_text='SEO alt text for the image', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_cover', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(choices=[('studio', 'Studio'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk', '5 BHK'), ('villa', 'Villa')], max_length=10)),
                ('image', models.ImageField(upload_to='properties/floor_plans/', validators=[apps.core.validators.validate_image_file])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='properties.property')),
            ],
            options={
                'verbose_name': 'Floor Plan',
                'ordering': ['bhk_type'],
                'unique_together': {('property', 'bhk_type')},
            },
        ),
        migrations.CreateModel(
            name='BHKConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk_type', models.CharField(choices=[('studio', 'Studio'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk', '5 BHK'), ('villa', 'Villa')], max_length=10)),
                ('area_sqft_min', models.PositiveIntegerField(help_text='Minimum area in sqft')),
                ('area_sqft_max', models.PositiveIntegerField(blank=True, help_text='Max area (for range display like 1304–1484 sqft)', null=True)),
                ('super_builtup_area', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for Price on Request', max_digits=14, null=True, validators=[apps.core.validators.validate_positive_price])),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('price_on_request', 'Price on Request')], default='available', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bhk_configs', to='properties.property')),
            ],
            options={
                'verbose_name': 'BHK Configuration',
                'ordering': ['bhk_type'],
                'unique_together': {('property', 'bhk_type')},
            },
        ),
    ]
