# Generated by Django 6.1.1 on 2026-09-22 05:08

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_lat_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Allowed: .mp4, .webm, .mov | Max size: 200MB', upload_to='properties/videos/', validators=[apps.core.validators.validate_video_file])),
                ('title', models.CharField(blank=True, help_text='Short title for this video clip', max_length=200)),
                ('video_type', models.CharField(choices=[('walkthrough', 'Property Walkthrough'), ('aerial', 'Aerial / Drone View'), ('testimonial', 'Client Testimonial'), ('construction', 'Construction Update'), ('other', 'Other')], db_index=True, default='walkthrough', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional custom thumbnail (auto-generated if blank)', null=True, upload_to='properties/video_thumbs/', validators=[apps.core.validators.validate_image_file])),
                ('duration_sec', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds (optional)', null=True)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display order — lower number shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Video',
                'verbose_name_plural': 'Property Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
