# Generated by Django 6.1.1 on 2026-09-21 11:35

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(help_text='Indian mobile number (10 digits, starts with 6-9)', max_length=15, validators=[apps.core.validators.validate_indian_mobile])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('inquiry_type', models.CharField(choices=[('call_back', 'Call Back'), ('site_visit', 'Book Site Visit'), ('brochure', 'Download Brochure'), ('general', 'General Inquiry')], default='call_back', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False, help_text="Mark True once you've followed up with this lead")),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this lead (not shown to user)')),
                ('source_page', models.CharField(blank=True, help_text='URL or page where form was submitted', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, help_text='Which property this inquiry is about (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_contacted', 'created_at'], name='leads_lead_is_cont_99bd16_idx'), models.Index(fields=['mobile'], name='leads_lead_mobile_0244d4_idx')],
            },
        ),
    ]
