# Generated by Django 6.1.1 on 2026-09-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='inquiry_type',
            field=models.CharField(choices=[('call_back', 'Call Back'), ('site_visit', 'Book Site Visit'), ('brochure', 'Download Brochure'), ('general', 'General Inquiry'), ('seller', 'Seller Inquiry')], default='call_back', max_length=20),
        ),
    ]
