# Generated by Django 6.1.1 on 2026-09-21 11:35

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on listing cards (max 500 chars)', max_length=500)),
                ('content', models.TextField(help_text='Full article content (HTML or Markdown)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/', validators=[apps.core.validators.validate_image_file])),
                ('featured_image_alt', models.CharField(blank=True, help_text='SEO alt text for featured image', max_length=200)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('read_time', models.PositiveSmallIntegerField(default=1, help_text='Estimated read time in minutes (auto-calculated)')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags: Ahmedabad, Investment, RERA, Gift City', max_length=500)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars). Defaults to post title if blank.', max_length=70, validators=[apps.core.validators.validate_meta_title])),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160, validators=[apps.core.validators.validate_meta_description])),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', 'published_at'], name='blog_blogpo_is_publ_dcd2a8_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx')],
            },
        ),
    ]
